services:
  - type: web
    name: gestor-laravel
    runtime: docker
    plan: free
    dockerCommand: /docker/entrypoint.sh
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: Sistema de Gestión
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-sweet-meadow-acu8tl0p-pooler.sa-east-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_3jSRL2fqIoec
      - key: DB_SSLMODE
        value: prefer
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DRIVER
        value: public
      - key: APP_URL
        fromService:
          type: web
          name: gestor-laravel
          property: defaultDomain
      - key: ASSET_URL
        fromService:
          type: web
          name: gestor-laravel
          property: defaultDomain

  - type: pserv
    name: gestor-db
    plan: free
    engine: postgres
    version: "15.0"
    ipAllowList: []
